### ISSUE TITLE
TIntegerArray.Remove

### ISSUE THREAD

**Issue by Joopi** [SRL/SRL#10]
If you set the boolean All to false (which it is by default) and it doesn't find that value in the array, it deletes the first index from the Arr anyways.
This is because if the index that you pass to delete, (in this case -1), is below 0, it will still delete first index in that array.

So I suggest you add to TIntegerArray.Del a check that the index is a natural number.

**Comment by Joopi** [comment]
Also I haven't checked the other TArrays.Remove but I assume it follows the same logic.

**Comment by slackydev** [comment]
Solved
