### ISSUE TITLE
ResetCTS

### ISSUE THREAD

**Issue by Joopi** [SRL/SRL#11]
Another piece of flawed Olly code...

`procedure ResetCTS(CTS: Integer);
  begin
    if (CTS = 2) then
      SetToleranceSpeed2Modifiers(0.2, 0.2);
    SetColorToleranceSpeed(CTS);
  end; `

If you use the TCTS2Color overloads it will only reset the CTS but not the hue and saturation.

**Comment by slackydev** [comment]
I dont get it, it looks fine to me.
If CTS is 2 then it reset both modifiers to what's default in simba `0.2`.

**Comment by Joopi** [comment]
The problem is more how the entire SRL.FindColors is done. SetCTS returns the CTS before it sets the cts settings. That CTS is then passed on to ResetCTS...
Difficult to explain but do test just using SRL.FindColors (TCTS2Color overload) and after that WriteLn Hue & Sat.

They will not be set to 0.2

**Comment by slackydev** [comment]
Aha, yeah I see it now.

**Comment by slackydev** [comment]
Should be resolved now.
