### ISSUE TITLE
TSRL.GetClickType() in misc.simba

### ISSUE THREAD

**Issue by Joopi** [SRL/SRL#12]
When having a chatbox interface up (I don't know if this applies to all conversations, but at least to some), the click type colors change. 255 (red) turns into 254 / 65535 (yellow) turns into 65278

For reference...
https://i.imgur.com/dTjW2YC.png

**Comment by Joopi** [comment]
my bad.

https://i.imgur.com/dTjW2YC.png

**Comment by Joopi** [comment]
And the black color (65536) is also converted to 0.
Does that make this thing hard to solve?

**Comment by slackydev** [comment]
@Olly- any issues with the following replacement? Are there any instances in RS where this could fail?
```pascal
function TSRL.GetClickType(Area: TBox): EClickType; override;
var
  BMP, trg: PtrUInt;
  TPA, red, yellow, tmp: TPointArray;
begin
  Result := ctNone;
  Area.LimitTo(GetClientBounds);
  BMP := BitmapFromClient(Area);
  trg := GetImageTarget();

  try
    SetTargetBitmap(BMP);
    Area := GetClientBounds();
    if (FindColorsTolerance(TPA, 65536, Area, 5)) then
    begin
      TPA := FindTPAEdges(TPA);
      FindColorsTolerance(yellow,65535, Area, 5);
      FindColorsTolerance(red,   255,   Area, 5);

      tmp := ReturnPointsNotInTPA(TPA, GetTPABounds(TPA));
      ClearTPAFromTPA(yellow, tmp);
      ClearTPAFromTPA(red,    tmp);

      if (Length(red) > 10) and (Length(Red) > Length(Yellow)) then
        Result := ctRed
      else if (Length(yellow) > 10) and (Length(Yellow) > Length(Red)) then
        Result := ctYellow;
    end;
  finally
    FreeTarget(GetImageTarget());
    FreeBitmap(BMP);
    SetImageTarget(trg);
  end;
end;
```
Not really my prettiest work, but I think it should do the trick. @Olly- will this leak? I think I got the target change handled correctly, but it's been a while.
