### ISSUE TITLE
SRL.isLoggedIn()

### ISSUE THREAD

**Issue by Joopi** [SRL/SRL#21]
Make an exception for people using RuneLite (or possibly other 3rd party clients) who use the default setting of having the report button replaced by a timer. isLoggedIn() returns false and it was a tedious task debugging all the steps that could possibly go wrong

if GetColor(443, 486) = $FFFFFF then //this line changed to something else.

**Comment by ollydev** [comment]
Untested, but should be fixed. Now uses `All` chat button text.
