### ISSUE TITLE
TRSLobby.IsOpen()

### ISSUE THREAD

**Issue by Joopi** [SRL/SRL#22]
Change the P = (361, 333) to (357, 333)

**Comment by TheTS** [comment]
Where is slackly

**Comment by Joopi** [comment]
The best way to counter color bots is to just make small useless changes knowing that there aren't enough active devs to do anything about it :/

**Comment by TheTS** [comment]
send in a pull request ill accept it

**Comment by Joopi** [comment]
Olly rewrote the way SRL handles client state. Admittedly I haven't tested the code but looking at it, it should work.

**Comment by ollydev** [comment]
it does, just tested. :)
