### ISSUE TITLE
Can we add Inventory.WaitCount

### ISSUE THREAD

**Issue by TheTS** [SRL/SRL#7]
This always comes in handy when doing basic skills (mining, wc, or looting etc.);

Maybe something like:

``` pascal
function TRSInventory.WaitCount(Count:Byte; Time:UInt32): Boolean;
var
  T: TCountDown;
begin
  Result := False;
  T.Init(Time);

  while (not T.IsFinished()) do
    if (self.Count() = Count) then
      Exit(True)
    else
      Wait(150 + Random(50));
end; 
```

EDIT: You know what would also be nice: Mouse.MultiClick(P, Chance, MaxClicks) like there is in SRL-6, or coiuld do Mouse.Click overload. Would be a cool addition since clicks (as opposed to movements) are all the rage.

**Comment by ollydev** [comment]
When I next do something RS related sure, or you can send a pull request.

**Comment by slackydev** [comment]
I first noticed this now. This seems like a good idea, I'll see if I can get it added soon. Unless someone beats me to it :p

**Comment by ollydev** [comment]
I was about to add it!

**Comment by TheTS** [comment]
Darn I knew I should have waited another 30 seconds
